// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcgifxoxllxruqldagkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZ2lmeG94bGx4cnVxbGRhZ2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NDUxNTksImV4cCI6MjA1NjIyMTE1OX0.GW3BJikTd8iPSeCjDCBH7qrkEgVtIeKiMWAJiwzrNnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);